### PR TITLE
Regenerate bindings for playdate SDK 2.0

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
https://sdk.play.date/changelog/#_2_0_0

Function for clearing the cache indeed appeared, example games run as before.
`generate_bindings.sh` script did not work for me until I've added more includes to bindgen, included in this PR too.

### CODE REVIEW

**Comment by boozook** [comment]
I can't test it right now on all platforms, so could be great it anyone tell me that it works properly.
Unfortunately we have a shortage of CI tests in this repository 🤷🏻‍♂️ that must be fixed in nearest future.

**Comment by SomeoneToIgnore** [comment]
Just in case, I have all 3 platforms but no idea what would be the good test(s) — if you can share those, I could run them.

**Review by boozook — APPROVED** [review]
LGTM 👍

**Comment by boozook** [comment]
@SomeoneToIgnore I suppose "good test(s)" could be 
- test build with latest crank on all platforms
  - for sim
  - for device
That's enough for today. But currently I working on "probably next build system" and there is also will be tests with run, I hope.

**Pull request merged**
